### ISSUE TITLE
the feature about charades-sta

### ISSUE THREAD

**Issue by onlyonewater** [wjun0830/QD-DETR#18]
hi, authors, could you provide the slowfast and clip feature about the charades-sta dataset? I want to train the model on it. thanks!!!

**Comment by wjun0830** [comment]
Hello.
We do not have them now but you can extract them following #1!

**Comment by onlyonewater** [comment]
ok, thanks, I will have a try!

**Comment by wjun0830** [comment]
We are very sorry for the inconvenience.
Charades-STA experiments with C3D features are actually conducted with I3D features and I3D benchmarking tables.
Features are provided [here](https://app.box.com/s/h0sxa5klco6qve5ahnz50ly2nksmuedw) from [VSLNET](https://github.com/26hzhang/VSLNet/tree/master).
