### ISSUE TITLE
Interference

### ISSUE THREAD

**Issue by Lonicer** [wjun0830/QD-DETR#2]
Hello, can I run the code in the run_on_video you provided on my own video like Moment-DETR? If possible, can you provide the best checkpoint of your training and validation process? Thanks!

**Comment by wjun0830** [comment]
Although we haven't tried it ourselves, you may be able to.

In addition, since we lost track of our best checkpoints, we provide one available now. There would not be a significant difference.
Checkpoints are available here [videoonly](https://www.dropbox.com/s/yygwyljw8514d9r/videoonly.ckpt?dl=0) and [video+audio](https://www.dropbox.com/s/hsc7jk21ppqasjt/videoaudio.ckpt?dl=0).

**Comment by Lonicer** [comment]
> Although we haven't tried it ourselves, you may be able to.
> 
> In addition, since we lost track of our best checkpoints, we provide one available now. There would not be a significant difference. Checkpoints are available here [videoonly](https://www.dropbox.com/s/yygwyljw8514d9r/videoonly.ckpt?dl=0) and [video+audio](https://www.dropbox.com/s/hsc7jk21ppqasjt/videoaudio.ckpt?dl=0).

Thanks!

**Comment by Lonicer** [comment]
Excuse me, why are both your code and Moment-DETR saliency prediction scores negative, while the Ground Truth annotations are non-negative? What is the purpose of this setting? Why not add an activation function? Thanks!




勾陈
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjun0830/QD-DETR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 晚上8:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjun0830/QD-DETR] Interference (Issue #2)





 
Although we haven't tried it ourselves, you may be able to.
 
In addition, since we lost track of our best checkpoints, we provide one available now. There would not be a significant difference.
 Checkpoints are available here videoonly and video+audio.

**Comment by wjun0830** [comment]
I don't think there will be much difference since I think the activation function only serves to adjust the weight of the loss.

**Comment by Lonicer** [comment]
Hello, sorry to bother you again, how did you confirm the evaluation indicators in the tvsum dataset? I ran your code and found that each category was predicted 5 times. Did you take the average of these five results? Or take the largest of them as the result? Thanks!
