### ISSUE TITLE
about feature extract

### ISSUE THREAD

**Issue by hhhhnwl** [wjun0830/QD-DETR#20]
1.To use the pretrain model, could you please share the script for slowfast feature extraction? 
2.Are the parameters for extracting CLIP features exactly the same as the moment-detr?

**Comment by hhhhnwl** [comment]
clip_len maybe set to 1?
python extract_feature/extract.py --dataflow --csv /output/csv/slowfast_info.csv \
    --batch_size 45 --num_decoding_thread 4 --clip_len 1 \
    TEST.CHECKPOINT_FILE_PATH /models/SLOWFAST_8x8_R50.pkl

**Comment by wjun0830** [comment]
Hello Thanks for the interest.
1. For the feature extraction, you can refer to [HERO github](https://github.com/linjieli222/HERO_Video_Feature_Extractor).
2. Yes, we followed the procedure from our baseline, Moment-DETR.
3. Yes, we set clip len to 1.
