### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'dict' and 'float'

### ISSUE THREAD

**Issue by ceyxasm** [wjun0830/QD-DETR#25]
QD-DETR-main/run_on_video/data_utils.py", line 89, in __call__
    tensor = tensor / 255.0

I cross-checked at tensor is indeed dict type.

**Comment by wjun0830** [comment]
Thanks for the interest. 
What experiment are you running?
You might want to check the environment.
Our python version is 3.7.4.

**Comment by ceyxasm** [comment]
@wjun0830 I was trying to run [run_on_video](https://github.com/wjun0830/QD-DETR/tree/main/run_on_video) experiment.
My version of python is 3.7.16

**Comment by wjun0830** [comment]
Do you mean that you ran the command "python run_on_video/run.py"?
When I ran the above command by myself, it does not yield any errors.

**Comment by ceyxasm** [comment]
There were tons of dependency issues which was causing it. Got it to work.
Hence closing.

**Comment by domeZhao** [comment]
> There were tons of dependency issues which was causing it. Got it to work. Hence closing.

Hi, @ceyxasm 
I encountered the same issue. Could you please share which dependencies were causing the problem and how you fixed it? Any help would be appreciated!

**Comment by ceyxasm** [comment]
Hey it was long back and I do not really remember.
But for debugging what I had done is added tons of breakpoints between tensor init and its division.
And somewhere I between I was able to localize the issue to be a dependency one.

**Comment by domeZhao** [comment]
Thanks for your prompt reply. I’ve successfully resolved the issue!
