### ISSUE TITLE
The I3D features about Charades-STA

### ISSUE THREAD

**Issue by ManLoveRice** [wjun0830/QD-DETR#26]
Hi, may I ask if the Charades dataset uses the I3D features provided by VSLNET? If yes, what is the value of your 'clip_len' parameter? If not, could you please provide the code for extracting video features?

**Comment by wjun0830** [comment]
Hello.
Yes right
Clip length is set to 0.5.

**Comment by ManLoveRice** [comment]
Thank you for your response. May I ask if the reason you set it to 0.5 is that the duration of the samples is 0.5 times the feature length?

**Comment by wjun0830** [comment]
It is because the features are extracted every 0.5 second.
I may be wrong since it's been a while.
You can check the feature length to make sure!
