### ISSUE TITLE
Fail to download TVsum dataset and could you please provide a new link？

### ISSUE THREAD

**Issue by sorrowyn** [wjun0830/QD-DETR#30]
![图片](https://github.com/wjun0830/QD-DETR/assets/19569162/9f429ed9-6a49-4177-9739-2e89a954266c)

**Comment by wjun0830** [comment]
You can download it from [here](https://drive.google.com/file/d/10Ji9MrlDK_4FdD3HotrVc407xVr4arsL/view?usp=sharing).

**Comment by sorrowyn** [comment]
> You can download it from [here](https://drive.google.com/file/d/10Ji9MrlDK_4FdD3HotrVc407xVr4arsL/view?usp=sharing).

Thanks for your help！This data has now been downloaded successfully.
