### ISSUE TITLE
TVSUM Result 

### ISSUE THREAD

**Issue by yaokunZ** [wjun0830/QD-DETR#31]
Excuse me, I found that there are five random seed values in the tvum code. After I reproduced your code, I found that the five results were very different. I would like to ask how the results in the paper were selected.

**Comment by wjun0830** [comment]
Although the result per domain differs from seed to seed, we found that there is not much difference in average value.
For example, our average scores for seeds 0, 1, 2, 3 are 0.837, 0.850, 0.847, 0.854.
seed | VT | VU | GA | MS | PK | PR | FM | BK | BT | DS | avg
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 0.87288 | 0.88385 | 0.87438 | 0.77149 | 0.85681 | 0.83521 | 0.77101 | 0.89937 | 0.87733 | 0.73021 | 0.837254
1 | 0.88222 | 0.87448 | 0.85601 | 0.84993 | 0.85847 | 0.86861 | 0.76448 | 0.91271 | 0.8916 | 0.73667 | 0.849518
2 | 0.87288 | 0.85 | 0.90844 | 0.87556 | 0.85653 | 0.83306 | 0.73771 | 0.87861 | 0.88549 | 0.77389 | 0.847217
3 | 0.88222 | 0.92 | 0.92062 | 0.80354 | 0.85622 | 0.87038 | 0.75566 | 0.86962 | 0.89653 | 0.76326 | 0.853805

We reported the result with seed 1.

**Comment by yaokunZ** [comment]
Thanks！
