### ISSUE TITLE
TVSUM data issue

### ISSUE THREAD

**Issue by yaokunZ** [wjun0830/QD-DETR#32]
![image](https://github.com/wjun0830/QD-DETR/assets/55798047/606e0688-33c7-4b1a-90c2-34de49d08075)
Why do we need to divide by 80 and multiply by 12?

**Comment by wjun0830** [comment]
We did that to normalize the saliency scores to a scale similar to the QVhighlights saliency score.

**Comment by yaokunZ** [comment]
But I found that the video length is not 80, why does normalization need to be divided by 80?
![image](https://github.com/wjun0830/QD-DETR/assets/55798047/9dbe4d75-417c-46f1-ad70-07e7f0762ae9)

**Comment by wjun0830** [comment]
It's not the length.
We normalized the scale of the saliency score

2023년 9월 20일 (수) 오후 2:42, zyk ***@***.***>님이 작성:

**Comment by yaokunZ** [comment]
Thanks! There are 20 scores per clip in TVSUM , but QVhighlights only has 3 saliency scores.
