### ISSUE TITLE
SharePoint: That didn't work - user cannot be found in the directory

### ISSUE THREAD

**Issue by HSPUPIL** [wjun0830/QD-DETR#33]
There was an error when I tried to download feature files for TVSum dataset from the Share Point link you gave.
![image](https://github.com/wjun0830/QD-DETR/assets/127296864/a4d2c448-2c97-49e1-87ea-76f4b8a061bb)

**Comment by Skaiyin** [comment]
How do u fix it? I meet the same error.

**Comment by wjun0830** [comment]
Please refer to Readme.
We have uploaded new instruction.
Thank you

2023년 11월 28일 (화) 오후 8:23, Shengkai Yin ***@***.***>님이 작성:
