### ISSUE TITLE
official feature files for QVHighlights dataset 

### ISSUE THREAD

**Issue by zsxzs** [wjun0830/QD-DETR#37]
Hi, can you provide the feature files? The original link is dead and the author of the dataset features is not available

**Comment by hzsun1995** [comment]
maybe you can find it in huggingface.

**Comment by zsxzs** [comment]
> maybe you can find it in huggingface.

Thank you a lot. I have found it

**Comment by sdracula** [comment]
> > maybe you can find it in huggingface.
> 
> Thank you a lot. I have found it

I can't find this file too. If it is convenient, could you share this file with me? Best wish for you.

**Comment by wjun0830** [comment]
Sorry for the late reply.
From now, you can also find from
[QVHighlight](https://drive.google.com/file/d/1LXsZZBsv6Xbg_MmNQOezw0QYKccjcOkP/view?usp=sharing)</b> 9.34GB.
