### ISSUE TITLE
About ablation study

### ISSUE THREAD

**Issue by MasterBeeee** [wjun0830/QD-DETR#38]
Thanks for your work, I have some questions on the ablation study.
1. In the Table4 in the paper, which is the ``Ablation study on QVHighlights val split``, is the (a) row Moment-detr? and if so, is the (b) row that Moment-detr simply with ``cross-attentive transformer encoder`` ?
2. What should I do If I want to do the same ablation experiment like （b） row , that is only using CATE？

**Comment by wjun0830** [comment]
1. You are right
2. if you want to apply cross attn on top of moment detr it would be easier if you simply add cross atten layer on top of moment detr implementation
