### ISSUE TITLE
Regarding results in Tables 1 and 2 of paper

### ISSUE THREAD

**Issue by nogaini** [wjun0830/QD-DETR#4]
Hello,

I have a question regarding your paper - are the scores reported in Tables 1 and 2 with or without pretraining on ASR captions?

Best,
Noga

**Comment by wjun0830** [comment]
Those scores are without pretraining.
Results with pretraining on asr can be found [here]( https://paperswithcode.com/sota/moment-retrieval-on-qvhighlights?p=query-dependent-video-representation-for)

**Comment by nogaini** [comment]
Thank you for the quick response! :) I had a look at the w/ PT scores in PapersWithCode, and it seems they are referenced from the Highlight Detection results table and moreover, they seem to be scores obtained by other models. For example, the QD-DETR only Video w/ PT score seems to be linked to the SL-Module method by Xu et al. (2021) - column PR. Similarly, the QD-DETR w/ PT score is linked to the sLSTM method by Zhang et al. (2016) - column BK. Is there a mistake, or am I reading this the wrong way?

**Comment by wjun0830** [comment]
Sorry, but I do not understand your question.
Besides, in the paper, there are no results with ASR-pretrained models for our method.

**Comment by nogaini** [comment]
Sorry for not being clear with my question. What I meant to ask is -  if you go [here](https://paperswithcode.com/paper/query-dependent-video-representation-for/review/?hl=100162), and hover over the score values for "w/ PT", it seems to refer to scores which are completely unrelated to the QD-DETR model. So I was wondering what you meant when you said that the results with ASR pre-training can be found in the link you provided?

**Comment by wjun0830** [comment]
Oh, sorry for confusing you.
In the paper, we didn't actually report the results after ASR-pretraining.
But for someone who might be interested in the results after ASR-pretraining, we pretrained QD-DETR with ASR captions first following the instructions on README and then trained QVhighlights dataset to obtain the numbers in the link.
Details for ASR-pretraining can be found in Moment-DETR and if you follow the instructions in README to pretrain first and then train on QVHighlights, you sure may be able to reproduce the numbers in the link.

**Comment by nogaini** [comment]
Ah, I see! Sorry, I guess I just got confused with the interface of the PapersWithCode website. Thank you for the quick clarification! :) Closing this issue now as it's been resolved.
