### ISSUE TITLE
How can i inference with a single video and get its output after downloading the checkpoints?

### ISSUE THREAD

**Issue by whycantfindaname** [wjun0830/QD-DETR#44]
Splendid work! But I wonder that how can i inference with a single video and get its output after downloading the checkpoints?

**Comment by wjun0830** [comment]
Are you trying to evaluate on your custom video?
If so, its easier to check "others" section in ReadMe in https://github.com/wjun0830/CGDETR/tree/main?tab=readme-ov-file#-others-custom-video-inference--training

**Comment by whycantfindaname** [comment]
> Are you trying to evaluate on your custom video? If so, its easier to check "others" section in ReadMe in https://github.com/wjun0830/CGDETR/tree/main?tab=readme-ov-file#-others-custom-video-inference--training

Thanks a lot!
