### ISSUE TITLE
About ActivityNet Dataset

### ISSUE THREAD

**Issue by Am1reux** [wjun0830/QD-DETR#45]
Hello,

I'm very interested in your work related to this topic. I'm currently conducting experiments on Moment Retrieval (MR) using QD-DETR on the ActivityNet dataset. However, the performance on ActivityNet is quite poor. Here are the specific metrics:
   "brief": {
        "MR-full-R1@0.5": 36.42,
        "MR-full-R1@0.7": 20.73,
        "MR-full-mAP": 26.96,
        "MR-full-mAP@0.5": 47.43,
        "MR-full-mAP@0.75": 25.38,
        "MR-long-mAP": 35.87,
        "MR-middle-mAP": 25.95,
        "MR-short-mAP": 15.22
    }
For these experiments, I'm using the I3D video features and Glove-extracted text features from [VSLNet](https://github.com/26hzhang/VSLNet). Here are the relevant hyperparameters from my opt.json file:

[opt.json](https://github.com/user-attachments/files/17348887/opt.json)

Since there are no experimental results on this dataset in the paper, I wanted to reach out and ask if you have conducted any experiments on this dataset. Additionally, I would greatly appreciate any suggestions you might have for improving my hyperparameters.

Thank you for your time and expertise.

**Comment by wjun0830** [comment]
For activitynet, we havent tried with this repo.
But when we tried with EaTR repo that used t include anet loader, we have also failed to get decent results.

Maybe to enhance the results for anet, it would be better to ask the authors of EaTR for how they did it.

**Comment by Am1reux** [comment]
Thank you so much for your kidness and help
