### ISSUE TITLE
poor performance on TACoS dataset

### ISSUE THREAD

**Issue by Psycho-9** [wjun0830/QD-DETR#46]
I reproduced your work locally on Video Moment Retrieval dataset, I used the charades-sta and tacos datasets provided by CG-DETR homepage link， the result on charades-sta is normal， but the result on tacos is abnormal ,the loss didn't converge and the R1iou0.5 is almost 0 , is this a problem about TACoS dataset?

**Comment by wjun0830** [comment]
As I have replied on other issue,. You may better check cliplen
