### ISSUE TITLE
no QVHighlisht test set label

### ISSUE THREAD

**Issue by Psycho-9** [wjun0830/QD-DETR#47]
Thanks for your great work. When I reproduce the QD-DERT on QVHighlight dataset, i found there's no test set groungtruth label, could you please provide the test set label or provide a link?

**Comment by wjun0830** [comment]
Hello.

Test label is not publicly available. check [here](https://github.com/wjun0830/QD-DETR/blob/main/standalone_eval/README.md)
You can evaluate your model on test set via [Codalab](https://codalab.lisn.upsaclay.fr/competitions/6937).

**Comment by Psycho-9** [comment]
thanks a lot
