### ISSUE TITLE
Missing opt.json file

### ISSUE THREAD

**Issue by nogaini** [wjun0830/QD-DETR#5]
Hi WonJun,

While running the command `bash qd_detr/scripts/inference.sh results/checkpoints/model_best.ckpt 'val'` (`{direc}` is replaced with my path), I'm getting a missing `opt.json` error: 

`FileNotFoundError: [Errno 2] No such file or directory: 'results/checkpoints/opt.json'`

It seems the test options file is missing?

Best,
Noga

**Comment by wjun0830** [comment]
Sorry for the inconvenience.
We now have uploaded opt.json. 
If you check the checkpoint under the results directory, the checkpoint is now provided with opt.json.
Thank you.

**Comment by nogaini** [comment]
Thank you for the quick resolution! :) Closing this issue now.
