### ISSUE TITLE
Missing umt_clip_text_features and umt_pann_features

### ISSUE THREAD

**Issue by nogaini** [wjun0830/QD-DETR#6]
Hi WonJun,

The `qd_detr/scripts/train_audio.sh` script makes use of `features/umt_clip_text_features` and `features/umt_pann_features`. However, these are missing in the `moment_detr_features.tar.gz` file. Could you upload these features as well, please?

Best,
Noga

**Comment by wjun0830** [comment]
Those files can be found in UMT's github!

**Comment by nogaini** [comment]
Ah okay, thanks! :)
