### ISSUE TITLE
About descrption of results file.

### ISSUE THREAD

**Issue by EdenGabriel** [wjun0830/QD-DETR#9]
Hello,    
    Thank you for your interesting work. I have some questions about your code and paper. Is the result in Table 1 of the paper corresponding to the results/video_checkpoint_best_hl_val_preds_metrics.json in the "results" folder?

Best,
Eden

**Comment by wjun0830** [comment]
Hello
Thanks for your interest

No. The provided json is for the validation set.
And the reported number is for the test set which you can get after you submit your model to the codalab.

Also, reported numbers are averaged on 5runs.

Thanks

**Comment by EdenGabriel** [comment]
> 

Thanks.
